/**
 * Documentation Manifest
 * 
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * This file is generated by: bun run generate-docs-manifest
 * 
 * To customize:
 * 1. Edit this file directly (changes will be overwritten on next generation)
 * 2. Or add metadata comments to markdown files (future feature)
 * 
 * Files discovered: 19
 * Generated: 2026-03-31T02:26:44.358Z
 */

export interface DocSection {
  /** Unique identifier (matches markdown filename without .md) */
  id: string;
  /** Display title */
  title: string;
  /** Icon emoji */
  icon: string;
  /** Short description */
  description: string;
  /** Display order within group */
  order: number;
  /** Tags for search/filtering */
  tags?: string[];
  /** Related section IDs */
  related?: string[];
}

export interface DocGroup {
  /** Unique identifier for URL routing */
  id: string;
  /** Display title */
  title: string;
  /** Description */
  description: string;
  /** Icon emoji */
  icon: string;
  /** Display order */
  order: number;
  /** Sections in this group */
  sections: DocSection[];
  /** Whether this group is expanded by default */
  expanded?: boolean;
}

/**
 * Documentation Groups Configuration
 * 
 * Auto-generated from markdown files in src/assets/docs/
 */
export const DOCS_MANIFEST: DocGroup[] = [
  {
    id: 'duckdb',
    title: 'DuckDB CRUD Integration',
    description: 'Column-oriented OLAP database for analytics and bulk operations',
    icon: '🦆',
    order: 1,
    expanded: false,
    sections: [
      {
        id: 'duckdb-api',
        title: 'DuckDB API Reference',
        icon: '🔌',
        description: 'Backend API documentation',
        order: 1,
        tags: ['duckdb', 'duckdb-api'],
      },
      {
        id: 'duckdb-architecture',
        title: 'DuckDB Architecture',
        icon: '🏗️',
        description: 'System architecture and design',
        order: 2,
        tags: ['duckdb', 'duckdb-architecture'],
      },
      {
        id: 'duckdb-performance',
        title: 'DuckDB Performance Guide',
        icon: '📖',
        description: 'Benchmarks and optimization',
        order: 3,
        tags: ['duckdb', 'duckdb-performance'],
      },
      {
        id: 'duckdb-quickstart',
        title: 'DuckDB Quick Start Guide',
        icon: '📖',
        description: 'Get started in 5 minutes',
        order: 4,
        tags: ['duckdb', 'duckdb-quickstart'],
      },
      {
        id: 'duckdb-schema',
        title: 'DuckDB Database Schema',
        icon: '📋',
        description: 'Table design and indexes',
        order: 5,
        tags: ['duckdb', 'duckdb-schema'],
      },
      {
        id: 'duckdb-vs-sqlite',
        title: 'DuckDB vs SQLite Comparison',
        icon: '🆚',
        description: 'Feature and performance comparison',
        order: 6,
        tags: ['duckdb', 'duckdb-vs-sqlite'],
      },
      {
        id: 'DUCKDB_CRUD_INTEGRATION',
        title: 'Production-Ready DuckDB CRUD Integration',
        icon: '📖',
        description: 'Production-Ready DuckDB CRUD Integration documentation',
        order: 7,
        tags: ['duckdb', 'DUCKDB-CRUD-INTEGRATION'],
      }
    ],
  },
  {
    id: 'sqlite',
    title: 'SQLite CRUD Integration',
    description: 'Row-oriented OLTP database for transactions and simple lookups',
    icon: '🗄️',
    order: 2,
    expanded: false,
    sections: [
      {
        id: 'sqlite-api',
        title: 'SQLite API Reference',
        icon: '🔌',
        description: 'Backend API documentation',
        order: 1,
        tags: ['sqlite', 'sqlite-api'],
      },
      {
        id: 'sqlite-architecture',
        title: 'SQLite Architecture',
        icon: '🏗️',
        description: 'System architecture and design',
        order: 2,
        tags: ['sqlite', 'sqlite-architecture'],
      },
      {
        id: 'sqlite-performance',
        title: 'SQLite Performance Guide',
        icon: '📖',
        description: 'Benchmarks and optimization',
        order: 3,
        tags: ['sqlite', 'sqlite-performance'],
      },
      {
        id: 'sqlite-quickstart',
        title: 'SQLite Quick Start Guide',
        icon: '📖',
        description: 'Get started in 5 minutes',
        order: 4,
        tags: ['sqlite', 'sqlite-quickstart'],
      },
      {
        id: 'sqlite-schema',
        title: 'SQLite Database Schema',
        icon: '📋',
        description: 'Table design and indexes',
        order: 5,
        tags: ['sqlite', 'sqlite-schema'],
      },
      {
        id: 'SQLITE_CRUD_INTEGRATION',
        title: 'Production-Ready SQLite CRUD Integration',
        icon: '📖',
        description: 'Production-Ready SQLite CRUD Integration documentation',
        order: 6,
        tags: ['sqlite', 'SQLITE-CRUD-INTEGRATION'],
      }
    ],
  },
  {
    id: 'comparison',
    title: 'Database Comparison',
    description: 'Choose the right database for your use case',
    icon: '⚖️',
    order: 3,
    expanded: false,
    sections: [
      {
        id: 'performance-comparison',
        title: 'Performance Comparison',
        icon: '🚀',
        description: 'Benchmarks and optimization',
        order: 1,
        tags: ['comparison', 'performance-comparison'],
      }
    ],
  },
  {
    id: 'production',
    title: 'Production Guide',
    description: 'Deploy to production with confidence',
    icon: '🚀',
    order: 4,
    expanded: false,
    sections: [
      {
        id: 'error-handling',
        title: 'Error Handling Guide',
        icon: '📖',
        description: 'Graceful error management',
        order: 1,
        tags: ['production', 'error-handling'],
      },
      {
        id: 'security-checklist',
        title: 'Security Checklist',
        icon: '🔒',
        description: 'Production security measures',
        order: 2,
        tags: ['production', 'security-checklist'],
      },
      {
        id: 'testing-guide',
        title: 'Testing Guide',
        icon: '📖',
        description: 'Unit and integration tests',
        order: 3,
        tags: ['production', 'testing-guide'],
      },
      {
        id: 'troubleshooting',
        title: 'Troubleshooting Guide',
        icon: '📖',
        description: 'Common issues and solutions',
        order: 4,
        tags: ['production', 'troubleshooting'],
      },
      {
        id: 'use-cases',
        title: 'Database Use Cases',
        icon: '🎯',
        description: 'Recommended use cases',
        order: 5,
        tags: ['production', 'use-cases'],
      }
    ],
  }
];

/**
 * Get all available documentation IDs
 */
export function getAllDocIds(): string[] {
  return DOCS_MANIFEST.flatMap(group => 
    group.sections.map(section => section.id)
  );
}

/**
 * Get a section by ID
 */
export function getSectionById(id: string): DocSection | undefined {
  for (const group of DOCS_MANIFEST) {
    const section = group.sections.find(s => s.id === id);
    if (section) return section;
  }
  return undefined;
}

/**
 * Get a group by ID
 */
export function getGroupById(id: string): DocGroup | undefined {
  return DOCS_MANIFEST.find(g => g.id === id);
}

/**
 * Search documentation by keyword
 */
export function searchDocs(keyword: string): { groups: DocGroup[]; sections: DocSection[] } {
  const lowerKeyword = keyword.toLowerCase();
  
  const matchingSections: DocSection[] = [];
  const matchingGroups: DocGroup[] = [];
  
  for (const group of DOCS_MANIFEST) {
    if (
      group.title.toLowerCase().includes(lowerKeyword) ||
      group.description.toLowerCase().includes(lowerKeyword)
    ) {
      matchingGroups.push(group);
    }
    
    for (const section of group.sections) {
      if (
        section.title.toLowerCase().includes(lowerKeyword) ||
        section.description.toLowerCase().includes(lowerKeyword) ||
        section.tags?.some(tag => tag.toLowerCase().includes(lowerKeyword))
      ) {
        matchingSections.push(section);
      }
    }
  }
  
  return { groups: matchingGroups, sections: matchingSections };
}

/**
 * Get related sections for a given section ID
 */
export function getRelatedSections(sectionId: string): DocSection[] {
  const section = getSectionById(sectionId);
  if (!section?.related) return [];
  
  return section.related
    .map(id => getSectionById(id))
    .filter((s): s is DocSection => s !== undefined);
}
